config/routes.rb
Rails.application.routes.draw do
  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to
  # Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the
  # :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being
  # the default of "spree".
  mount Spree::Core::Engine, at: '/'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Spree::Core::Engine.add_routes do

  namespace :admin do
    resources :taxonomies do  
		resources :taxons do
		  resources :taxon_certificates, :path => "certificates" do
			collection do
			  post :update_positions
			end
		  end
		end
	end
  end

  namespace :admin do
    resources :taxonomies do  
		resources :taxons do
		  resources :taxon_interiors, :path => "interiors" do
			collection do
			  post :update_positions
			end
		  end
		end
	end
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :taxonomies do
		resources :taxons do	  
			resources :taxon_certificates, :path => "certificates"
		end
      end
    end
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :taxonomies do
		resources :taxons do	  
			resources :taxon_interiors, :path => "interiors"
		end
      end
    end
  end
  
end

app/controllers/spree/api/v1/taxons_controller.rb
module Spree
  module Api
    module V1
      class TaxonsController < Spree::Api::BaseController
        def index
          @taxons = if taxonomy
                      taxonomy.root.children
                    elsif params[:ids]
                      Spree::Taxon.includes(:children).accessible_by(current_ability).where(id: params[:ids].split(','))
                    else
                      Spree::Taxon.includes(:children).accessible_by(current_ability).order(:taxonomy_id, :lft)
                    end
          @taxons = @taxons.ransack(params[:q]).result
          @taxons = @taxons.page(params[:page]).per(params[:per_page])
          respond_with(@taxons)
        end

        def show
          @taxon = taxon
          respond_with(@taxon)
        end

        def jstree
          show
        end

        def new; end

        def create
          authorize! :create, Taxon
          @taxon = Spree::Taxon.new(taxon_params)
          @taxon.taxonomy_id = params[:taxonomy_id]
          taxonomy = Spree::Taxonomy.find_by(id: params[:taxonomy_id])

          if taxonomy.nil?
            @taxon.errors.add(:taxonomy_id, I18n.t('spree.api.invalid_taxonomy_id'))
            invalid_resource!(@taxon) and return
          end

          @taxon.parent_id = taxonomy.root.id unless params[:taxon][:parent_id]

          if @taxon.save
            respond_with(@taxon, status: 201, default_template: :show)
          else
            invalid_resource!(@taxon)
          end
        end

        def update
          authorize! :update, taxon
		  taxon.build_icon(attachment: taxon_icon_params[:attachment]) if params[:image]	  
          if taxon.update(taxon_params)
            respond_with(taxon, status: 200, default_template: :show)
          else
            invalid_resource!(taxon)
          end
  
        end

        def destroy
          authorize! :destroy, taxon
          taxon.destroy
          respond_with(taxon, status: 204)
        end

        def products
          # Returns the products sorted by their position with the classification
          # Products#index does not do the sorting.
          taxon = Spree::Taxon.find(params[:id])
          @products = taxon.products.ransack(params[:q]).result
          @products = @products.page(params[:page]).per(params[:per_page] || 500)
          render 'spree/api/v1/products/index'
        end

        private

        def taxonomy
          if params[:taxonomy_id].present?
            @taxonomy ||= Spree::Taxonomy.accessible_by(current_ability, :show).find(params[:taxonomy_id])
          end
        end

        def taxon
          @taxon ||= taxonomy.taxons.accessible_by(current_ability, :show).find(params[:id])
        end

        def permitted_taxon_icon_attributes
          [:alt, :attachment, :position, :viewable_type, :viewable_id]
        end

        def taxon_icon_params
          if params[:image] && !params[:image].empty?
            params.require(:image).permit(permitted_taxon_icon_attributes)
          else
            {}
          end
		end

        def taxon_params
          if params[:taxon] && !params[:taxon].empty?
            params.require(:taxon).permit(permitted_taxon_attributes)
          else
            {}
          end
        end
      end
    end
  end
end

app/views/spree/admin/taxons/_form.html.erb
<div data-hook="admin_inside_taxon_form">
  <div class="row">
    <div class="col-xs-12 col-md-5">
        <%= f.field_container :name, class: ['form-group'] do %>
          <%= content_tag(:span, "ID:" + @taxon.id.to_s, class: 'required') %>
          <%= f.error_message_on :id %>
        <% end %>

      <%= f.field_container :name, class: ['form-group'] do %>
        <%= f.label :name, Spree.t(:name) %> <span class="required">*</span>
        <%= text_field :taxon, :name, class: 'form-control' %>
        <%= f.error_message_on :name, class: 'error-message' %>
      <% end %>

      <%= f.field_container :permalink, class: ['form-group'] do %>
        <%= label_tag :permalink_part, Spree.t(:permalink) %> <span class="required">*</span>
        <%= text_field_tag :permalink_part, @permalink_part, class: 'form-control', required: true %>
        <p class="help-block" id="permalink_part_display">
          <%= @taxon.permalink.split('/')[0...-1].join('/') + '/' %>
        </p>
      <% end %>

      <%= f.field_container :icon, class: ['form-group'] do %>
        <%= f.label :icon, Spree.t(:icon) %>
        <%= image_tag main_app.url_for(@taxon.icon.try(:attachment)) if @taxon.icon %>
        <%= f.file_field :icon %>
      <% end %>
    </div>
    <div class="col-xs-12 col-md-7">
      <%= f.field_container :description, class: ['form-group'] do %>
        <%= f.label :description, Spree.t(:description) %>
        <%= f.text_area :description, class: 'form-control', rows: 6 %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <%= f.field_container :taxon_props, class: ['form-group'] do %>
      <%= f.label :taxon_props, Spree.t(:taxon_props) %>
      <%= f.text_area :taxon_props, class: 'form-control', rows: 6 %>
    <% end %>
  </div>

  <div class="row">
	<H3>Сертификаты</H3>
	<%= render partial: "/spree/admin/taxons/taxon_certificate" %>
  </div>
  <div class="row">
	<H3>В интерьере</H3>
	<%= render partial: "/spree/admin/taxons/taxon_interior" %>
  </div>

  <%= f.field_container :meta_title, class: ['form-group'] do %>
    <%= f.label :meta_title, Spree.t(:meta_title) %>
    <%= f.text_field :meta_title, class: 'form-control', rows: 6 %>
  <% end %>

  <%= f.field_container :meta_description, class: ['form-group'] do %>
    <%= f.label :meta_description, Spree.t(:meta_description) %>
    <%= f.text_field :meta_description, class: 'form-control', rows: 6 %>
  <% end %>

  <%= f.field_container :meta_keywords, class: ['form-group'] do %>
    <%= f.label :meta_keywords, Spree.t(:meta_keywords) %>
    <%= f.text_field :meta_keywords, class: 'form-control', rows: 6 %>
  <% end %>
</div>

app/views/spree/admin/taxons/_taxon_certificate.html.erb
<%= button_link_to(Spree.t(:new_image), spree.new_admin_taxonomy_taxon_taxon_certificate_url(@taxon.taxonomy_id, @taxon), { class: "btn-success", icon: 'add', id: 'new_image_link' }) if can? :create, Spree::TaxonCertificate %>

<% unless @taxon.certificates.any? %>
  <div class="alert alert-warning">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::TaxonCertificate)) %>.
  </div>
<% else %>
  <table class="table sortable" data-hook="images_table" data-sortable-link="<%= update_positions_admin_taxonomy_taxon_taxon_certificates_url(@taxon.taxonomy_id, @taxon) %>">
    <thead>
      <tr data-hook="images_header">
        <th colspan="2">
          <%= Spree.t(:thumbnail) %>
        </th>
        <th>
          <%= Spree.t(:alt_text) %>
        </th>
        <th class="actions"></th>
      </tr>
    </thead>

    <tbody>
      <% (@taxon.certificates).each do |image| %>
        <tr id="<%= spree_dom_id image %>" data-hook="images_row">
          <td class="move-handle text-center">
            <% if can? :edit, image %>
              <span class="icon icon-move handle"></span>
            <% end %>
          </td>
          <td class="image">
            <% if %w(application/pdf application/zip).include?(image.attachment.content_type) %>          
              <%= link_to image.attachment.filename, main_app.rails_blob_path(image.attachment, disposition: "attachment") %>
            <% else %>
              <%= link_to image_tag(main_app.url_for(image.url(:mini))), main_app.url_for(image.url(:product)) %>
            <% end %>
          </td>
          <td><%= image.alt %></td>
          <td class="actions actions-2 text-right">
            <%= link_to_with_icon('edit', Spree.t(:edit), spree.edit_admin_taxonomy_taxon_taxon_certificate_url(@taxon.taxonomy_id, @taxon, image), class: 'btn btn-primary btn-sm', no_text: true, data: { action: 'edit' }) if can? :edit, image %>
            <%= link_to_delete(image, { url: spree.admin_taxonomy_taxon_taxon_certificate_url(@taxon.taxonomy_id, @taxon, image), no_text: true }) if can? :destroy, image %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/spree/admin/taxons/_taxon_interior.html.erb
<%= button_link_to(Spree.t(:new_image), spree.new_admin_taxonomy_taxon_taxon_interior_url(@taxon.taxonomy_id, @taxon), { class: "btn-success", icon: 'add', id: 'new_image_link' }) if can? :create, Spree::TaxonInterior %>

<% unless @taxon.interiors.any? %>
  <div class="alert alert-warning">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::TaxonInterior)) %>.
  </div>
<% else %>
  <table class="table sortable" data-hook="images_table" data-sortable-link="<%= update_positions_admin_taxonomy_taxon_taxon_interiors_url(@taxon.taxonomy_id, @taxon) %>">
    <thead>
      <tr data-hook="images_header">
        <th colspan="2">
          <%= Spree.t(:thumbnail) %>
        </th>
        <th>
          <%= Spree.t(:alt_text) %>
        </th>
        <th class="actions"></th>
      </tr>
    </thead>

    <tbody>
      <% (@taxon.interiors).each do |image| %>
        <tr id="<%= spree_dom_id image %>" data-hook="images_row">
          <td class="move-handle text-center">
            <% if can? :edit, image %>
              <span class="icon icon-move handle"></span>
            <% end %>
          </td>
          <td class="image">
            <%= link_to image_tag(main_app.url_for(image.url(:mini))), main_app.url_for(image.url(:product)) %>
          </td>
          <td><%= image.alt %></td>
          <td class="actions actions-2 text-right">
            <%= link_to_with_icon('edit', Spree.t(:edit), spree.edit_admin_taxonomy_taxon_taxon_interior_url(@taxon.taxonomy_id, @taxon, image), class: 'btn btn-primary btn-sm', no_text: true, data: { action: 'edit' }) if can? :edit, image %>
            <%= link_to_delete(image, { url: spree.admin_taxonomy_taxon_taxon_interior_url(@taxon.taxonomy_id, @taxon, image), no_text: true }) if can? :destroy, image %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/spree/admin/taxons/_taxon_table.html.erb
<table class="table table-condensed table-bordered">
  <thead>
    <tr data-hook="taxons_header">
      <th><%= Spree.t(:name) %></th>
      <th><%= Spree.t(:path) %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% taxons.each do |taxon| %>
      <tr id="<%= spree_dom_id(taxon) %>" data-hook="taxons_row">
        <td><%= taxon.name %></td>
        <td><%= taxon_path taxon %></td>
        <td class="actions">
          <%= link_to_delete taxon, url: remove_admin_product_taxon_url(@product, taxon), name: icon('delete') + ' ' + Spree.t(:remove) %>
        </td>
      </tr>
    <% end %>
    <% if taxons.empty? %>
      <tr data-hook="taxons_none"><td colspan="3"><%= Spree.t(:none) %>.</td></tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/taxons/edit.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(:taxonomies), spree.admin_taxonomies_url %> /
  <%= link_to @taxonomy.name, spree.edit_admin_taxonomy_url(@taxonomy) %> /
  <%= @taxon.name %>
<% end %>

<%# Because otherwise the form would attempt to use to_param of @taxon %>
<% form_url = admin_taxonomy_taxon_path(@taxonomy.id, @taxon.id) %>

<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @taxon } %>

<%= form_for [:admin, @taxonomy, @taxon], method: :put, url: form_url, html: { multipart: true } do |f| %>
  <%= render 'form', f: f %>

  <div class="form-actions" data-hook="buttons">
    <%= button Spree.t('actions.update'), 'save' %>
    <span class="or"><%= Spree.t(:or) %></span>
    <%= button_link_to Spree.t('actions.cancel'), edit_admin_taxonomy_url(@taxonomy), icon: "remove" %>
  </div>
<% end %>

app/views/spree/admin/taxons/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:taxons) %>
<% end %>

<div class="taxon-products-view">
  <div class="form-group">
    <%= text_field_tag :taxon_id %>
  </div>

  <ul id="taxon_products" class="taxon"></ul>

  <%= render partial: "spree/admin/products/autocomplete", formats: :js %>
</div>